apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app-ex2
  namespace: app-ex2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-python-app-ex2
  template:
    metadata:
      labels:
        app: my-python-app-ex2
    spec:
      containers:
      - name: my-python-app-ex2
        image: munish62/my-python-app-ex2:v1
        ports:
        - containerPort: 5000

